# Generated by Django 6.1.1 on 2026-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_round_match_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
