# Generated by Django 6.1.1 on 2026-09-17 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_status_prediction_total_goals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.round'),
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('starts_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('next_round_name', models.CharField(default='Następna runda', max_length=100)),
                ('next_round', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='matches.round')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DraftPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('resolution_method', models.CharField(blank=True, choices=[('VOTE', 'Vote'), ('RANDOM_TIE', 'Random tie draw')], max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='matches.draft')),
                ('match_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_pairs_as_a', to='matches.match')),
                ('match_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_pairs_as_b', to='matches.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_draft_pairs', to='matches.match')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DraftVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='matches.draftpair')),
                ('selected_match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_votes', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='draftpair',
            constraint=models.CheckConstraint(condition=models.Q(('match_a', models.F('match_b')), _negated=True), name='draft_pair_distinct_matches'),
        ),
        migrations.AddConstraint(
            model_name='draftpair',
            constraint=models.UniqueConstraint(fields=('draft', 'match_a'), name='draft_pair_unique_match_a'),
        ),
        migrations.AddConstraint(
            model_name='draftpair',
            constraint=models.UniqueConstraint(fields=('draft', 'match_b'), name='draft_pair_unique_match_b'),
        ),
        migrations.AddConstraint(
            model_name='draftvote',
            constraint=models.UniqueConstraint(fields=('user', 'pair'), name='one_draft_vote_per_user_pair'),
        ),
    ]
