# Generated by Django 6.1.1 on 2026-09-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_round_draft_draftpair_draftvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpair',
            name='day_number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
