# Generated by Django 6.1.1 on 2026-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_draftpair_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpair',
            name='day_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
