# Generated by Django 6.1.1 on 2026-09-17 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_draftpair_day_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip', models.CharField(choices=[('BANKER', 'Banker'), ('DOUBLE_PICK', 'Double Pick'), ('CHANGE_MIND', "I've Changed My Mind"), ('SWAP', 'Swap'), ('GOOOOOOOOAL', 'Goooooooal!')], max_length=16)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('goal_team', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_assignments', to='matches.match')),
                ('replacement_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='swap_replacements', to='matches.match')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_assignments', to='matches.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'round', 'chip'), name='one_chip_type_per_round'), models.UniqueConstraint(fields=('user', 'round', 'match'), name='one_chip_per_match_round')],
            },
        ),
    ]
