# Generated by Django 6.1.1 on 2026-09-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_chipassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='modifier_resolution_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='draft',
            name='modifier_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='matches.competition')),
                ('champion_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_seasons', to='matches.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='competition_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.competitionseason'),
        ),
        migrations.AddField(
            model_name='draft',
            name='modifier_options',
            field=models.ManyToManyField(blank=True, related_name='draft_options', to='matches.globalmodifier'),
        ),
        migrations.AddField(
            model_name='draft',
            name='winning_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_drafts', to='matches.globalmodifier'),
        ),
        migrations.AddField(
            model_name='round',
            name='active_global_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_rounds', to='matches.globalmodifier'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='matches.team'),
        ),
        migrations.CreateModel(
            name='DraftModifierVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_votes', to='matches.draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.globalmodifier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'draft'), name='one_modifier_vote_per_draft')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(fields=('competition', 'season_label'), name='unique_competition_season'),
        ),
    ]
