# Generated by Django 6.1.1 on 2026-09-17 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_competition_globalmodifier_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typy_points', models.IntegerField(default=0)),
                ('gole_points', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='matches.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'round'), name='one_user_round_score')],
            },
        ),
    ]
