# Generated by Django 6.1.1 on 2026-09-18 06:57

import django.db.models.deletion
from django.db import migrations, models


def create_candidate_memberships(apps, schema_editor):
    DraftPair = apps.get_model('matches', 'DraftPair')
    DraftPairCandidate = apps.get_model('matches', 'DraftPairCandidate')
    DraftPairCandidate.objects.bulk_create([
        DraftPairCandidate(draft_id=pair.draft_id, pair_id=pair.id, match_id=pair.match_a_id, side='A')
        for pair in DraftPair.objects.all()
    ] + [
        DraftPairCandidate(draft_id=pair.draft_id, pair_id=pair.id, match_id=pair.match_b_id, side='B')
        for pair in DraftPair.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_userroundscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPairCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('away_goals__isnull', True), ('home_goals__isnull', True)), models.Q(('away_goals__isnull', False), ('home_goals__isnull', False)), _connector='OR'), name='match_score_is_complete_or_empty'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_round'),
        ),
        migrations.AddField(
            model_name='draftpaircandidate',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_memberships', to='matches.draft'),
        ),
        migrations.AddField(
            model_name='draftpaircandidate',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_candidate_memberships', to='matches.match'),
        ),
        migrations.AddField(
            model_name='draftpaircandidate',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_memberships', to='matches.draftpair'),
        ),
        migrations.RunPython(create_candidate_memberships, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='draftpaircandidate',
            constraint=models.UniqueConstraint(fields=('draft', 'match'), name='one_candidate_per_draft'),
        ),
        migrations.AddConstraint(
            model_name='draftpaircandidate',
            constraint=models.UniqueConstraint(fields=('pair', 'side'), name='one_candidate_per_pair_side'),
        ),
    ]
