# Generated by Django 6.1.1 on 2026-09-18 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_draftpaircandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ranking_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='Match50Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_match50_season')],
            },
        ),
        migrations.AddField(
            model_name='round',
            name='match50_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='matches.match50season'),
        ),
    ]
