# Generated by Django 6.1.1 on 2026-09-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_achievement_match_finished_at_trophyfinish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user_achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='matches.userachievement')),
            ],
        ),
        migrations.CreateModel(
            name='MatchKickoffSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff_snapshot', to='matches.match')),
            ],
        ),
    ]
