# Generated by Django 6.1.1 on 2026-09-20 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_round_early_bird_at_round_early_bird_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('context', models.JSONField(default=dict)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='max_stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='achievement',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementnotification',
            name='event_key',
            field=models.CharField(default='unlock', max_length=120),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='current_tier',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='achievementnotification',
            name='user_achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matches.userachievement'),
        ),
        migrations.AddConstraint(
            model_name='achievementnotification',
            constraint=models.UniqueConstraint(fields=('user_achievement', 'event_key'), name='unique_achievement_notification'),
        ),
        migrations.AddField(
            model_name='achievementoccurrence',
            name='user_achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='matches.userachievement'),
        ),
        migrations.AddConstraint(
            model_name='achievementoccurrence',
            constraint=models.UniqueConstraint(fields=('user_achievement', 'event_key'), name='unique_achievement_occurrence'),
        ),
    ]
