# Generated by Django 6.1.1 on 2026-09-20 09:23

from django.db import migrations, models


TEAM_SHIRTS = {
    "Arsenal": ("#d71920", "#ffffff", "CONTRAST_SLEEVES"),
    "Aston Villa": ("#670e36", "#95bfe5", "CONTRAST_SLEEVES"),
    "Atletico Madrid": ("#d71920", "#ffffff", "VERTICAL_STRIPES"),
    "Barcelona": ("#004d98", "#a50044", "VERTICAL_STRIPES"),
    "Bayer Leverkusen": ("#e32221", "#111111", "HALVES"),
    "Bayern Munich": ("#dc052d", "#ffffff", "SOLID"),
    "Borussia Dortmund": ("#fde100", "#111111", "SOLID"),
    "Bournemouth": ("#d71920", "#111111", "VERTICAL_STRIPES"),
    "Brentford": ("#e30613", "#ffffff", "VERTICAL_STRIPES"),
    "Brighton & Hove Albion": ("#0057b8", "#ffffff", "VERTICAL_STRIPES"),
    "Burnley": ("#6c1d45", "#99d6ea", "CONTRAST_SLEEVES"),
    "Chelsea": ("#034694", "#ffffff", "SOLID"),
    "Crystal Palace": ("#1b458f", "#c4122e", "VERTICAL_STRIPES"),
    "Everton": ("#003399", "#ffffff", "SOLID"),
    "Fulham": ("#ffffff", "#111111", "SOLID"),
    "Inter": ("#0057b8", "#111111", "VERTICAL_STRIPES"),
    "Juventus": ("#ffffff", "#111111", "VERTICAL_STRIPES"),
    "Leeds United": ("#ffffff", "#1d428a", "SOLID"),
    "Liverpool": ("#c8102e", "#ffffff", "SOLID"),
    "Manchester City": ("#6cabdd", "#ffffff", "SOLID"),
    "Manchester United": ("#da291c", "#111111", "SOLID"),
    "Milan": ("#fb090b", "#111111", "VERTICAL_STRIPES"),
    "Napoli": ("#12a0d7", "#ffffff", "SOLID"),
    "Newcastle United": ("#ffffff", "#111111", "VERTICAL_STRIPES"),
    "Nottingham Forest": ("#dd0000", "#ffffff", "SOLID"),
    "RB Leipzig": ("#ffffff", "#d5003e", "SOLID"),
    "Real Madrid": ("#ffffff", "#d4af37", "SOLID"),
    "Sevilla": ("#ffffff", "#d71920", "SOLID"),
    "Sunderland": ("#eb172b", "#ffffff", "VERTICAL_STRIPES"),
    "Tottenham": ("#ffffff", "#132257", "SOLID"),
    "West Ham United": ("#7a263a", "#1bb1e7", "CONTRAST_SLEEVES"),
    "Wolverhampton Wanderers": ("#fdb913", "#111111", "SOLID"),
}


def populate_team_shirts(apps, schema_editor):
    Team = apps.get_model("matches", "Team")
    alias = schema_editor.connection.alias
    for name, (primary, secondary, pattern) in TEAM_SHIRTS.items():
        Team.objects.using(alias).filter(name=name).update(
            shirt_primary=primary, shirt_secondary=secondary, shirt_pattern=pattern,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_preserve_achievement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='shirt_pattern',
            field=models.CharField(choices=[('SOLID', 'Solid'), ('VERTICAL_STRIPES', 'Vertical stripes'), ('HORIZONTAL_HOOPS', 'Horizontal hoops'), ('CONTRAST_SLEEVES', 'Contrast sleeves'), ('HALVES', 'Half-and-half')], default='SOLID', max_length=24),
        ),
        migrations.AddField(
            model_name='team',
            name='shirt_primary',
            field=models.CharField(default='#94a3b8', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='shirt_secondary',
            field=models.CharField(default='#e2e8f0', max_length=7),
        ),
        migrations.RunPython(populate_team_shirts, migrations.RunPython.noop),
    ]
