# Generated by Django 6.1.1 on 2026-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_team_shirt_visuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipassignment',
            name='chip',
            field=models.CharField(choices=[('BANKER', 'Banker'), ('DOUBLE_PICK', 'Double Pick'), ('CHANGE_MIND', 'VAR'), ('SWAP', 'Swap'), ('GOOOOOOOOAL', 'Goooooooal!')], max_length=16),
        ),
    ]
