# Generated by Django 6.1.1 on 2026-09-21 12:12

import django.db.models.deletion
from zoneinfo import ZoneInfo
from django.db import migrations, models


def backfill(apps, schema_editor):
    alias = schema_editor.connection.alias
    Match = apps.get_model("matches", "Match")
    Pair = apps.get_model("matches", "DraftPair")
    Alternative = apps.get_model("matches", "MatchAlternative")
    for match in Match.objects.using(alias).all().iterator():
        week = match.kickoff.astimezone(ZoneInfo("Europe/Warsaw")).isocalendar()
        Match.objects.using(alias).filter(pk=match.pk).update(automatic_kw_year=week.year, automatic_kw_week=week.week)
    # Preserve exactly the relationship selected by the former .first() lookup.
    for pair in Pair.objects.using(alias).filter(resolved_at__isnull=False, winner__isnull=False).order_by("day_number", "id"):
        loser = pair.match_b_id if pair.winner_id == pair.match_a_id else pair.match_a_id
        Alternative.objects.using(alias).get_or_create(match_id=pair.winner_id,
            defaults={"alternative_id": loser, "source_pair_id": pair.pk})


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_round_frozen_match_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='competition',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='provider_season',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='automatic_kw_week',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='automatic_kw_year',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='kw_override_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='kw_override_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='provider_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='provider_status',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='match',
            name='provider_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='api_football_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['automatic_kw_year', 'automatic_kw_week'], name='match_auto_kw_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(fields=('competition', 'provider_season'), name='unique_provider_season'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kw_override_week__isnull', True), ('kw_override_year__isnull', True)), models.Q(('kw_override_week__gte', 1), ('kw_override_week__isnull', False), ('kw_override_week__lte', 53), ('kw_override_year__isnull', False)), _connector='OR'), name='kw_override_complete'),
        ),
        migrations.AddField(
            model_name='matchalternative',
            name='alternative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_for', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchalternative',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_alternative', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchalternative',
            name='source_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='matches.draftpair'),
        ),
        migrations.AddConstraint(
            model_name='matchalternative',
            constraint=models.CheckConstraint(condition=models.Q(('match', models.F('alternative')), _negated=True), name='distinct_swap_alternative'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
