# Generated by Django 6.1.1 on 2026-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_prediction_optional_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='team_history_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='team_history_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
